### ISSUE TITLE
Criar Protótipo do ambiente do jogo

### ISSUE THREAD

**Issue by priscylla** [EduAmbiental/geral#4]

**Comment by priscylla** [comment]
Criar Tela principal do jogo onde serão visualizados:
- Fases
- Caminho até a Lagoa

**Comment by EliveltonCristiano** [comment]
![telateste](https://cloud.githubusercontent.com/assets/6800027/6999929/0e2b29c4-dbee-11e4-93e3-15a48b1d2a6c.png)

**Comment by EliveltonCristiano** [comment]
Prototipo da tela principal do jogo.
